# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Cartographer_config = debug

else ifeq ($(config),release)
  Cartographer_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Cartographer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Cartographer:
ifneq (,$(Cartographer_config))
	@echo "==== Building Cartographer ($(Cartographer_config)) ===="
	@${MAKE} --no-print-directory -C . -f Cartographer.make config=$(Cartographer_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Cartographer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Cartographer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"